# This is a basic workflow to help you get started with Actions

name: sync-fork

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: show-fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
        run: |
          gh repo list  --limit 200 --fork --json nameWithOwner
  
      - name: sync-fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
        run: |
          gh repo list  --limit 200 --fork --json nameWithOwner  --jq '.[].nameWithOwner' | xargs -n1  gh repo sync

